---
- name: Test DHCP helper
  hosts: cisco
  vars:
    creds:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"

  tasks:
    - ios_facts:
        provider: "{{ creds }}"
      delegate_to: pylab10b.twb-tech.com

    - name: Check for extra DHCP helpers
      ios_command:
        provider: "{{ creds }}"
        commands:
          - "show run interface {{ item }}"
      with_items: "{{ ansible_net_interfaces }}"
      register: new_output
      delegate_to: pylab10b.twb-tech.com

