---
- name: NAPALM gather information on IOS
  hosts: cisco
  tasks:
    - block:
        - name: Gather information
          napalm_get_facts:
            hostname: "{{ ansible_host }}"
            username: "{{ username }}"
            password: "{{ password }}"
            dev_os: "{{ device_type }}"
            filter: [facts]
          register: result
    
        - name: Debuggging
          debug: var=result
